INSERT Clients VALUES(20, 'Dubosc', 'Frank', '12 avenue des flots bleus', '76140', 'Petit-Quevilly');
INSERT Clients VALUES(21, 'Boon', 'Dany', '22 rue des Ch''tis', '59280', 'Armentières');
INSERT Clients VALUES(22, 'Elmaleh', 'Gad', '45 rue du sentier', '75001', 'Paris');
INSERT Clients VALUES(23, 'Dujardin', 'Jean', 'rue Brice', '92500', 'Rueil-Malmaison');
INSERT Clients VALUES(24, 'Marceau', 'Sophie', 'Boulevard de la Boom', '75010', 'Paris');
INSERT Clients VALUES(25, 'Merad', 'Kad', 'Rue du petit nicolas', '91130', 'Ris-Orangis');
INSERT Clients VALUES(26, 'Seigner', 'Mathilde', '357 rue du Camping', '75012', 'Paris');
INSERT Clients VALUES(27, 'Reno', 'Jean', '78 Boulevard de Léon', '51200', 'Montmirail'); 
INSERT Clients VALUES(28, 'Lanvin', 'Gérard', '84 avenue de l''aile ou la cuisse', '92100', 'Boulogne-Billancourt');
INSERT Clients VALUES(29, 'Tautou', 'Audrey', 'rue de Montmartre', '63110', 'Beaumont');
INSERT Clients VALUES(30, 'Cotillard', 'Marion', '45 rue de la Môme', '13001', 'Marseille');
INSERT Clients VALUES(31, 'Duris', 'Romain', '76 rue de l''arnaqueur', '06000', 'Nice');
INSERT Clients VALUES(32, 'Depardieu', 'Gérard', '57 rue du conte de Monté-Cristo', '36000', 'Châteauroux');
INSERT Clients VALUES(33, 'Youn', 'Michaël', 'rue de la beuze', '92150', 'Suresnes');
INSERT Clients VALUES(34, 'Poelvoorde', 'Benoît', '22 rue du Boulet', '22500', 'Paimpol');
INSERT Clients VALUES(35, 'Paradis', 'Vanessa', '12 rue des arnaqueurs', '94100', 'Saint-Maur-des-Fossés');
INSERT Clients VALUES(36, 'Wilson', 'Lambert', '100 rue de Dieu', '92200', 'Neuilly-sur-Seine');
INSERT Clients VALUES(37, 'Garcia', 'José', '65 rue de la vérité', '75001', 'Paris');
INSERT Clients VALUES(38, 'Luchini', 'Fabrice', '73 rue de Beaumarchais', '75016', 'Paris');
INSERT Clients VALUES(39, 'Baye', 'Nathalie', '33 rue de Vénus', '27150', 'Mainneville');
INSERT Clients VALUES(40, 'Magimel', 'Benoît', '47 rue des petits mouchoirs', '33950', 'Lège-Cap-Ferret');
INSERT Clients VALUES(41, 'Cluzet', 'François', '7 rue des apprentis', '75018', 'Paris');
INSERT Clients VALUES(42, 'Frot', 'Catherine', 'rue Odette', '69110', 'Sainte Foy-lès-Lyon');
INSERT Clients VALUES(43, 'Dupontel', 'Albert', '11 impasse de Bernie', '78100', 'Saintermain-en-Laye');
INSERT Clients VALUES(44, 'Huppert', 'Isabelle', '8 rue des femmes', '75002', 'Paris');
INSERT Clients VALUES(45, 'Deneuve', 'Catherine', '12 rue de Rochefort', '50100', 'Cherbourg-Octeville');
INSERT Clients VALUES(46, 'de France', 'Cécile', '17 rue de l''auberge espagnole', '08000', 'Charlesville-Mézières');

