
INSERT INTO CATEGORIES(code_cat, libelle_cat) VALUES (60,'Webcams');
SET IDENTITY_INSERT CATEGORIES ON
INSERT INTO CATEGORIES(code_cat, libelle_cat) VALUES (60,'Webcams');
SET IDENTITY_INSERT CATEGORIES OFF