
------------------------------------------------------------------------------------------
insert into genres_film values ('AC','Action')
insert into genres_film values ('AM','Amour')
insert into genres_film values ('AV','Aventure')
insert into genres_film values ('CD','Comédie dramatique')
insert into genres_film values ('CE','Comédie d''espionnage')
insert into genres_film values ('CF','Comédie fantastique')
insert into genres_film values ('CO','Comédie') 
insert into genres_film values ('CP','Comédie policière')
insert into genres_film values ('DA','Danse')
insert into genres_film values ('DH','Drame historique')
insert into genres_film values ('DM','Drame musical')
insert into genres_film values ('DO','Documentaire')
insert into genres_film values ('DP','Drame psychologique')
insert into genres_film values ('DR','Drame')
insert into genres_film values ('EN','Enfants')
insert into genres_film values ('FA','Fantastique')
insert into genres_film values ('GU','Guerre')
insert into genres_film values ('HI','Historique')
insert into genres_film values ('HO','Horreur')
insert into genres_film values ('MU','Musical')
insert into genres_film values ('PO','Policier')
insert into genres_film values ('SF','Science-fiction')
insert into genres_film values ('TH','Thriller')
insert into genres_film values ('WE','Western')


